project_id = "bzadclztipjxmhrtckwf"

[functions.get-mapbox-token]
verify_jwt = false

[functions.reverse-geocode]
verify_jwt = false

[functions.fetch-external-events]
verify_jwt = false

[functions.osm_ingest]
verify_jwt = false

[functions.tm_ingest]
verify_jwt = false

[functions.eb_ingest]
verify_jwt = false
