// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzadclztipjxmhrtckwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6YWRjbHp0aXBqeG1ocnRja3dmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMDU4NDEsImV4cCI6MjA3MTY4MTg0MX0.0rH5FhMJr7bNFjN0KLpRjt7Qfuhe-EnZbRzW4C1ZG6Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});